# 1. FROM: Definimos la imagen base.
FROM python:3.9-slim

# 2. WORKDIR: Establecemos el directorio de trabajo dentro del contenedor.
# Es como hacer "cd /app" automáticamente al entrar.
WORKDIR /app

# 3. COPY: Copiamos los archivos de tu laptop al contenedor.
# El primer punto (.) es tu carpeta actual.
# El segundo punto (.) es la carpeta /app dentro del contenedor.
COPY . .

# 4. CMD: El comando que se ejecutará al iniciar el contenedor.
# Le dice a Docker: "Ejecuta python sobre el archivo main.py"
CMD ["python", "main.py"]

# Nota: En proyectos reales de Data Science, 
# aquí agregaríamos un paso 
# RUN pip install -r requirements.txt 
# para instalar librerías como Pandas o NumPy, 
# pero como tu script solo usa Python estándar, 
# no es necesario hoy.